### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by linusdan** [DotOS/android_packages_providers_DownloadProvider#1]
Hello! I'm trying compiling with new updates, but i got this error:

`ERROR: /home/dan/android/dot-o/packages/providers/DownloadProvider/src/com/android/providers/downloads/DownloadProvider.java:131.17: Syntax error on token "MY_DOWNLOADS_ID_HEADERS", ( expected after this token`

`ERROR: /home/dan/android/dot-o/packages/providers/DownloadProvider/src/com/android/providers/downloads/DownloadProvider.java:1169.13: SqlSelection cannot be resolved to a type`

`ERROR: /home/dan/android/dot-o/packages/providers/DownloadProvider/src/com/android/providers/downloads/DownloadProvider.java:1171.9: SqlSelection cannot be resolved to a type`

`ERROR: /home/dan/android/dot-o/packages/providers/DownloadProvider/src/com/android/providers/downloads/DownloadProvider.java:1171.38: SqlSelection cannot be resolved to a type`

`ERROR: /home/dan/android/dot-o/packages/providers/DownloadProvider/src/com/android/providers/downloads/DownloadProvider.java:1183.25: Syntax error, insert "}" to complete MethodBody
`

in previous version works fine (r46).

**Comment by mohancm** [comment]
Fixed, you can force-sync and compile now 👍
